vich_uploader:
  db_driver: orm

  mappings:
    curriculum_vitae:
      uri_prefix: /images/cv
      upload_destination: "%kernel.project_dir%/public/images/cv"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
